"""Initial migration

Revision ID: a1964fd76888
Revises: 
Create Date: 2026-10-08 14:26:20.828396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1964fd76888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload_commit', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('event_hash'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_audit_events_sequence'), 'audit_events', ['sequence'], unique=False, schema='audit')
    op.create_table('compatibility_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.String(), nullable=False),
    sa.Column('blood_type', sa.String(), nullable=False),
    sa.Column('hla_typing', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_compatibility_profiles_id'), 'compatibility_profiles', ['id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_compatibility_profiles_ot_id'), 'compatibility_profiles', ['ot_id'], unique=True, schema='clinical')
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity_vault'
    )
    op.create_index(op.f('ix_identity_vault_hospitals_id'), 'hospitals', ['id'], unique=False, schema='identity_vault')
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_name', sa.String(), nullable=False),
    sa.Column('encrypted_dob', sa.String(), nullable=False),
    sa.Column('encrypted_identifier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity_vault'
    )
    op.create_index(op.f('ix_identity_vault_persons_id'), 'persons', ['id'], unique=False, schema='identity_vault')
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity_vault'
    )
    op.create_index(op.f('ix_identity_vault_token_blocklist_id'), 'token_blocklist', ['id'], unique=False, schema='identity_vault')
    op.create_index(op.f('ix_identity_vault_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=True, schema='identity_vault')
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='matching'
    )
    op.create_index(op.f('ix_matching_policy_versions_id'), 'policy_versions', ['id'], unique=False, schema='matching')
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sequence'], ['audit.audit_events.sequence'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_checkpoints_id'), 'checkpoints', ['id'], unique=False, schema='audit')
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.String(), nullable=False),
    sa.Column('organ_type', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['identity_vault.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_offers_id'), 'offers', ['id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_offers_ot_id'), 'offers', ['ot_id'], unique=False, schema='clinical')
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.String(), nullable=False),
    sa.Column('organ_type', sa.String(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['identity_vault.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clinical'
    )
    op.create_index(op.f('ix_clinical_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False, schema='clinical')
    op.create_index(op.f('ix_clinical_waitlist_entries_ot_id'), 'waitlist_entries', ['ot_id'], unique=False, schema='clinical')
    op.create_table('pseudonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ot_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['identity_vault.persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity_vault'
    )
    op.create_index(op.f('ix_identity_vault_pseudonyms_id'), 'pseudonyms', ['id'], unique=False, schema='identity_vault')
    op.create_index(op.f('ix_identity_vault_pseudonyms_ot_id'), 'pseudonyms', ['ot_id'], unique=True, schema='identity_vault')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('COORDINATOR', 'CLINICIAN', 'HLA_LAB', 'AUDITOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['identity_vault.hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity_vault'
    )
    op.create_index(op.f('ix_identity_vault_users_email'), 'users', ['email'], unique=True, schema='identity_vault')
    op.create_index(op.f('ix_identity_vault_users_id'), 'users', ['id'], unique=False, schema='identity_vault')
    op.create_table('match_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('policy_hash', sa.String(), nullable=False),
    sa.Column('offer_hash', sa.String(), nullable=False),
    sa.Column('waitlist_hash', sa.String(), nullable=False),
    sa.Column('output_hash', sa.String(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['clinical.offers.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['matching.policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='matching'
    )
    op.create_index(op.f('ix_matching_match_runs_id'), 'match_runs', ['id'], unique=False, schema='matching')
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_run_id', sa.Integer(), nullable=False),
    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('trace_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['match_run_id'], ['matching.match_runs.id'], ),
    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['clinical.waitlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='matching'
    )
    op.create_index(op.f('ix_matching_candidates_id'), 'candidates', ['id'], unique=False, schema='matching')
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_run_id', sa.Integer(), nullable=False),
    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['identity_vault.users.id'], ),
    sa.ForeignKeyConstraint(['match_run_id'], ['matching.match_runs.id'], ),
    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['clinical.waitlist_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='matching'
    )
    op.create_index(op.f('ix_matching_decisions_id'), 'decisions', ['id'], unique=False, schema='matching')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_decisions_id'), table_name='decisions', schema='matching')
    op.drop_table('decisions', schema='matching')
    op.drop_index(op.f('ix_matching_candidates_id'), table_name='candidates', schema='matching')
    op.drop_table('candidates', schema='matching')
    op.drop_index(op.f('ix_matching_match_runs_id'), table_name='match_runs', schema='matching')
    op.drop_table('match_runs', schema='matching')
    op.drop_index(op.f('ix_identity_vault_users_id'), table_name='users', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_users_email'), table_name='users', schema='identity_vault')
    op.drop_table('users', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_pseudonyms_ot_id'), table_name='pseudonyms', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_pseudonyms_id'), table_name='pseudonyms', schema='identity_vault')
    op.drop_table('pseudonyms', schema='identity_vault')
    op.drop_index(op.f('ix_clinical_waitlist_entries_ot_id'), table_name='waitlist_entries', schema='clinical')
    op.drop_index(op.f('ix_clinical_waitlist_entries_id'), table_name='waitlist_entries', schema='clinical')
    op.drop_table('waitlist_entries', schema='clinical')
    op.drop_index(op.f('ix_clinical_offers_ot_id'), table_name='offers', schema='clinical')
    op.drop_index(op.f('ix_clinical_offers_id'), table_name='offers', schema='clinical')
    op.drop_table('offers', schema='clinical')
    op.drop_index(op.f('ix_audit_checkpoints_id'), table_name='checkpoints', schema='audit')
    op.drop_table('checkpoints', schema='audit')
    op.drop_index(op.f('ix_matching_policy_versions_id'), table_name='policy_versions', schema='matching')
    op.drop_table('policy_versions', schema='matching')
    op.drop_index(op.f('ix_identity_vault_token_blocklist_jti'), table_name='token_blocklist', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_token_blocklist_id'), table_name='token_blocklist', schema='identity_vault')
    op.drop_table('token_blocklist', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_persons_id'), table_name='persons', schema='identity_vault')
    op.drop_table('persons', schema='identity_vault')
    op.drop_index(op.f('ix_identity_vault_hospitals_id'), table_name='hospitals', schema='identity_vault')
    op.drop_table('hospitals', schema='identity_vault')
    op.drop_index(op.f('ix_clinical_compatibility_profiles_ot_id'), table_name='compatibility_profiles', schema='clinical')
    op.drop_index(op.f('ix_clinical_compatibility_profiles_id'), table_name='compatibility_profiles', schema='clinical')
    op.drop_table('compatibility_profiles', schema='clinical')
    op.drop_index(op.f('ix_audit_audit_events_sequence'), table_name='audit_events', schema='audit')
    op.drop_table('audit_events', schema='audit')
    # ### end Alembic commands ###
